name: CI Tests

on: [push, pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Setup Nextflow ${{ matrix.nextflow }}
        uses: nf-core/setup-nextflow@v1
        with:
          version: "latest-edge"
          
      - name: Install nf-test
        run: |
          wget -qO- get.nf-test.com | bash  -s 0.9.0-rc2
          sudo mv nf-test /usr/local/bin/
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: "genepi/mtdna-server-2"
          cache-from: type=gha          
          cache-to: type=gha,mode=max
        
      - name: Run Tests 
        run:  nf-test test
